name: Maven Build and Test
on:
    workflow_call:
        inputs:
            java-version:
                type: string
                default: '17'
            distribution:
                type: string
                default: 'corretto'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-java@v4
            with:
                java-version: ${{ inputs.java-version }}
                distribution: ${{ inputs.distribution }}
                cache: 'maven'

          - name: Build with Maven
            run: mvn -B package --file pom.xml -DskipTests

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-java@v4
            with:
                java-version: ${{ inputs.java-version }}
                distribution: ${{ inputs.distribution }}
                cache: 'maven'

          - name: Test with Maven
            run: mvn test
